import os
from github import Github, GithubException

def open_pr(
    repo_url: str,
    fixes: list[dict],
    score_result: dict,
    github_token: str | None = None,
) -> str | None:
    """
    Create a branch on the repo, commit all fixes, and open a PR.
    Returns the PR URL or None on failure.
    """
    if not fixes:
        return None

    token = github_token or os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("Missing GitHub token for PR creation.")

    g = Github(token)

    # Parse owner/repo from URL
    # Handles: https://github.com/owner/repo or https://github.com/owner/repo.git
    parts = repo_url.rstrip("/").replace(".git", "").split("/")
    owner, repo_name = parts[-2], parts[-1]

    try:
        repo = g.get_repo(f"{owner}/{repo_name}")
    except GithubException as e:
        raise ValueError(f"Cannot access repo {owner}/{repo_name}: {e}")

    default_branch = repo.default_branch
    base_sha = repo.get_branch(default_branch).commit.sha

    branch_name = "deploywatch/production-readiness-fixes"

    # Create or reset branch
    try:
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
    except GithubException:
        # Branch already exists — update it
        ref = repo.get_git_ref(f"heads/{branch_name}")
        ref.edit(base_sha, force=True)

    # Commit each fix
    for fix in fixes:
        file_path = fix["file"]
        new_content = fix["new_content"]

        try:
            existing = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                file_path,
                f"fix: {fix['explanation'][:72]}",
                new_content,
                existing.sha,
                branch=branch_name,
            )
        except GithubException:
            # File doesn't exist yet — create it
            repo.create_file(
                file_path,
                f"feat: {fix['explanation'][:72]}",
                new_content,
                branch=branch_name,
            )

    # Build PR body
    fix_lines = "\n".join(
        f"- **`{f['file']}`** — {f['explanation']}" for f in fixes
    )
    score = score_result["score"]
    grade = score_result["grade"]

    body = f"""## DeployWatch: Production Readiness Fixes

**Score before:** {score}/100 — {grade}

### Changes made
{fix_lines}

### Why these fixes matter
These changes were automatically identified and generated by [DeployWatch](https://github.com/deploywatch/deploywatch) — an AI-powered production readiness agent.

> Review each change carefully before merging. The agent targets the highest-impact issues but you know your codebase best.
"""

    try:
        pr = repo.create_pull(
            title="DeployWatch: Production Readiness Fixes",
            body=body,
            head=branch_name,
            base=default_branch,
        )
        return pr.html_url
    except GithubException as e:
        # PR already exists
        if "already exists" in str(e).lower():
            pulls = repo.get_pulls(state="open", head=f"{owner}:{branch_name}")
            for p in pulls:
                return p.html_url
        raise ValueError(f"Failed to open PR: {e}")
