from github import Github, GithubException
from api.config import GITHUB_TOKEN


def open_pr(repo_url: str, fixes: list[dict], score: dict) -> str | None:
    if not fixes or not GITHUB_TOKEN:
        return None

    g = Github(GITHUB_TOKEN)
    parts = repo_url.rstrip("/").replace(".git", "").split("/")
    owner, repo_name = parts[-2], parts[-1]

    try:
        repo = g.get_repo(f"{owner}/{repo_name}")
    except GithubException as e:
        raise ValueError(f"Cannot access repo: {e}")

    default_branch = repo.default_branch
    base_sha = repo.get_branch(default_branch).commit.sha
    branch = "deploywatch/production-readiness-fixes"

    try:
        repo.create_git_ref(f"refs/heads/{branch}", base_sha)
    except GithubException:
        repo.get_git_ref(f"heads/{branch}").edit(base_sha, force=True)

    for fix in fixes:
        try:
            existing = repo.get_contents(fix["file"], ref=branch)
            repo.update_file(fix["file"], f"fix: {fix['explanation'][:72]}",
                             fix["new_content"], existing.sha, branch=branch)
        except GithubException:
            repo.create_file(fix["file"], f"feat: {fix['explanation'][:72]}",
                             fix["new_content"], branch=branch)

    fix_lines = "\n".join(f"- **`{f['file']}`** — {f['explanation']}" for f in fixes)
    body = f"""## DeployWatch: Production Readiness Fixes

**Score:** {score['score']}/100 — {score['grade']}

### Changes
{fix_lines}

> Auto-generated by DeployWatch. Review before merging.
"""

    try:
        pr = repo.create_pull(
            title="DeployWatch: Production Readiness Fixes",
            body=body,
            head=branch,
            base=default_branch,
        )
        return pr.html_url
    except GithubException:
        for p in repo.get_pulls(state="open", head=f"{owner}:{branch}"):
            return p.html_url
        return None
